import streamlit as st
from fpdf import FPDF

# Page Configuration
st.set_page_config(
    page_title="CiviCost AI",
    page_icon="🏗️",
    layout="wide"
)

# Function to generate PDF Reports
def generate_pdf(project_title, summary_data):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    
    # Header Section
    pdf.cell(0, 10, "CiviCost AI - Structural Estimation Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Category: {project_title}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)
    
    # Table Header
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(100, 8, "Item Description", border=1, fill=True)
    pdf.cell(90, 8, "Value / Cost", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    
    # Table Content
    pdf.set_font("Helvetica", "", 10)
    for key, value in summary_data.items():
        pdf.cell(100, 8, str(key), border=1)
        pdf.cell(90, 8, str(value), border=1, new_x="LMARGIN", new_y="NEXT")
        
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 8, "Generated by CiviCost AI - Civil Engineering Assistant", align="R")
    
    return bytes(pdf.output())

# Main Header
st.title("🏗️ CiviCost AI - Civil Engineering Assistant")
st.write("Calculate construction materials, reinforcement quantities, and estimated costs with ease.")

# Sidebar Navigation
st.sidebar.header("📌 Select Estimator")
calc_type = st.sidebar.selectbox(
    "Choose Calculation Type:",
    [
        "Concrete Volume & Material Calculator", 
        "Rebar (Steel) Calculator",
        "Brickwork Estimator", 
        "Plastering Estimator"
    ]
)

st.divider()

# 1. Concrete Calculator
if calc_type == "Concrete Volume & Material Calculator":
    st.subheader("🧱 Concrete Mix & Material Estimator")
    
    # Structural Member Selection
    element_type = st.radio(
        "Select Structural Element:",
        ["Slab", "Beam", "Column", "Footing", "Staircase"],
        horizontal=True
    )
    
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        length = st.number_input("Length (ft)", min_value=0.1, value=10.0, step=0.5)
    with col2:
        width = st.number_input("Width (ft)", min_value=0.1, value=10.0, step=0.5)
    with col3:
        thickness = st.number_input("Thickness / Depth (inches)", min_value=0.1, value=5.0, step=0.5)
    with col4:
        num_elements = st.number_input("Number of Elements", min_value=1, value=1, step=1)
        
    col_g1, col_g2 = st.columns(2)
    with col_g1:
        concrete_grade = st.selectbox(
            "Concrete Grade (Mix Ratio)",
            [
                "M10 — 1:3:6 (PCC / Lean Concrete)",
                "M15 — 1:2:4 (General RCC Work)",
                "M20 — 1:1.5:3 (Standard RCC Member)",
                "M25 — 1:1:2 (Heavy Structural RCC)"
            ],
            index=1
        )
    with col_g2:
        wastage_pct = st.slider("Concrete Wastage (%)", min_value=0, max_value=15, value=5)
        
    cement_price = st.sidebar.number_input("Cement Price (per bag - BDT)", value=550)
    sand_price = st.sidebar.number_input("Sand Price (per CFT - BDT)", value=45)
    chips_price = st.sidebar.number_input("Coarse Aggregate Price (per CFT - BDT)", value=120)

    if st.button("Calculate Concrete", type="primary"):
        # Single element wet volume in CFT
        single_wet_vol = length * width * (thickness / 12.0)
        total_wet_vol = single_wet_vol * num_elements
        
        # Dry volume calculation with wastage
        dry_vol = total_wet_vol * 1.54
        dry_vol += dry_vol * (wastage_pct / 100.0)
        
        # Extract ratio numbers from selected string
        ratio_str = concrete_grade.split("—")[1].split("(")[0].strip()
        c_r, s_r, a_r = map(float, ratio_str.split(":"))
        total_ratio = c_r + s_r + a_r
        
        cement_cft = (c_r / total_ratio) * dry_vol
        cement_bags = cement_cft / 1.25
        sand_cft = (s_r / total_ratio) * dry_vol
        chips_cft = (a_r / total_ratio) * dry_vol
        
        # Water calculation (approx 25 liters per bag of cement)
        water_liters = cement_bags * 25
        
        total_cost = (cement_bags * cement_price) + (sand_cft * sand_price) + (chips_cft * chips_price)

        st.success(f"**Total Concrete Volume ({num_elements} {element_type}s):** {total_wet_vol:.2f} CFT (Includes {wastage_pct}% Wastage)")
        
        m1, m2, m3, m4, m5 = st.columns(5)
        m1.metric("Cement Required", f"{cement_bags:.2f} Bags")
        m2.metric("Sand Required", f"{sand_cft:.2f} CFT")
        m3.metric("Aggregate Required", f"{chips_cft:.2f} CFT")
        m4.metric("Water Needed", f"{water_liters:.0f} Liters")
        m5.metric("Estimated Cost", f"BDT {total_cost:,.2f}")
        
        # PDF Generation
        report_data = {
            "Element Type": f"{element_type} (Qty: {num_elements})",
            "Concrete Grade": concrete_grade,
            "Total Wet Volume": f"{total_wet_vol:.2f} CFT",
            "Wastage Percentage": f"{wastage_pct}%",
            "Cement Required": f"{cement_bags:.2f} Bags",
            "Sand Required": f"{sand_cft:.2f} CFT",
            "Coarse Aggregate Required": f"{chips_cft:.2f} CFT",
            "Water Required": f"~{water_liters:.0f} Liters",
            "Estimated Total Cost": f"BDT {total_cost:,.2f}"
        }
        pdf_bytes = generate_pdf(f"Concrete Mix Estimation ({element_type})", report_data)
        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_bytes,
            file_name=f"concrete_{element_type.lower()}_report.pdf",
            mime="application/pdf"
        )

# 2. Rebar Calculator
elif calc_type == "Rebar (Steel) Calculator":
    st.subheader("⚙️ Rebar (Steel) Quantity & Weight Estimator")
    
    col1, col2, col3 = st.columns(3)
    with col1:
        bar_size = st.selectbox("Bar Diameter (mm)", [8, 10, 12, 16, 20, 25])
    with col2:
        num_bars = st.number_input("Number of Bars", min_value=1, value=10, step=1)
    with col3:
        bar_length = st.number_input("Length per Bar (ft)", min_value=0.1, value=39.5, step=0.5)
        
    steel_price_kg = st.sidebar.number_input("Steel Price (per kg - BDT)", value=98.0)
    wastage_pct = st.sidebar.slider("Wastage Allowance (%)", min_value=0, max_value=15, value=5)

    if st.button("Calculate Rebar", type="primary"):
        total_length_ft = num_bars * bar_length
        # Unit weight formula: W (kg/ft) = (d^2) / 533
        unit_weight_kg_ft = (bar_size ** 2) / 533.0
        base_weight_kg = total_length_ft * unit_weight_kg_ft
        
        wastage_kg = base_weight_kg * (wastage_pct / 100.0)
        total_weight_kg = base_weight_kg + wastage_kg
        total_weight_ton = total_weight_kg / 1000.0
        total_cost = total_weight_kg * steel_price_kg

        st.success(f"**Total Rebar Length:** {total_length_ft:.2f} ft")
        
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Unit Weight", f"{unit_weight_kg_ft:.3f} kg/ft")
        c2.metric("Total Weight (KG)", f"{total_weight_kg:.2f} kg")
        c3.metric("Total Weight (Ton)", f"{total_weight_ton:.3f} Ton")
        c4.metric("Estimated Cost", f"BDT {total_cost:,.2f}")
        
        # PDF Generation
        report_data = {
            "Bar Size": f"{bar_size} mm",
            "Total Number of Bars": f"{num_bars} Nos",
            "Single Bar Length": f"{bar_length} ft",
            "Total Rebar Length": f"{total_length_ft:.2f} ft",
            "Wastage Allowance": f"{wastage_pct}%",
            "Total Weight Required": f"{total_weight_kg:.2f} kg ({total_weight_ton:.3f} Ton)",
            "Estimated Total Cost": f"BDT {total_cost:,.2f}"
        }
        pdf_bytes = generate_pdf(f"Rebar ({bar_size}mm) Weight Estimation", report_data)
        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_bytes,
            file_name=f"rebar_{bar_size}mm_report.pdf",
            mime="application/pdf"
        )

# 3. Brickwork Calculator
elif calc_type == "Brickwork Estimator":
    st.subheader("🧱 Brickwork & Mortar Estimator")
    
    col1, col2, col3 = st.columns(3)
    with col1:
        wall_length = st.number_input("Wall Length (ft)", min_value=0.1, value=20.0)
    with col2:
        wall_height = st.number_input("Wall Height (ft)", min_value=0.1, value=10.0)
    with col3:
        wall_thickness = st.selectbox("Wall Thickness", ["5 inch", "10 inch"])
        
    brick_unit_price = st.sidebar.number_input("Price per Brick (BDT)", value=12.5)

    if st.button("Calculate Brickwork", type="primary"):
        wall_area = wall_length * wall_height
        total_bricks = wall_area * 5 if wall_thickness == "5 inch" else wall_area * 10
        brick_cost = total_bricks * brick_unit_price
        
        st.success(f"**Total Wall Area:** {wall_area:.2f} Sq. Ft.")
        
        c1, c2 = st.columns(2)
        c1.metric("Bricks Required", f"{int(total_bricks)} Pcs")
        c2.metric("Estimated Brick Cost", f"BDT {brick_cost:,.2f}")
        
        # PDF Generation
        report_data = {
            "Wall Area": f"{wall_area:.2f} Sq. Ft.",
            "Wall Thickness": wall_thickness,
            "Total Bricks Required": f"{int(total_bricks)} Pcs",
            "Estimated Brick Cost": f"BDT {brick_cost:,.2f}"
        }
        pdf_bytes = generate_pdf("Brickwork Estimation", report_data)
        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_bytes,
            file_name="brickwork_report.pdf",
            mime="application/pdf"
        )

# 4. Plastering Calculator
elif calc_type == "Plastering Estimator":
    st.subheader("🖌️ Wall & Ceiling Plastering Estimator")
    
    col1, col2, col3 = st.columns(3)
    with col1:
        plaster_area = st.number_input("Plaster Area (Sq. Ft.)", min_value=1.0, value=500.0)
    with col2:
        plaster_thick = st.selectbox("Plaster Thickness", ["0.5 inch (12 mm)", "0.75 inch (18 mm)", "0.25 inch (6 mm)"])
    with col3:
        mix_ratio = st.selectbox("Mix Ratio (Cement : Sand)", ["1:3 (Ceiling)", "1:4 (Outer Wall)", "1:5 (Inner Wall)", "1:6 (Inner Wall)"])
        
    cement_price = st.sidebar.number_input("Cement Price (per bag - BDT)", value=550)
    sand_price = st.sidebar.number_input("Sand Price (per CFT - BDT)", value=45)
    wastage_pct = st.sidebar.slider("Plaster Wastage (%)", min_value=0, max_value=15, value=5)

    if st.button("Calculate Plaster", type="primary"):
        # Thickness conversion
        if "0.25" in plaster_thick:
            thick_ft = 0.25 / 12.0
        elif "0.5" in plaster_thick:
            thick_ft = 0.5 / 12.0
        else:
            thick_ft = 0.75 / 12.0
            
        wet_vol = plaster_area * thick_ft
        dry_vol = wet_vol * 1.33  # Dry volume multiplier
        
        # Add wastage
        dry_vol += dry_vol * (wastage_pct / 100.0)
        
        # Ratio Calculation
        ratio_parts = mix_ratio.split("(")[0].strip().split(":")
        c_part = float(ratio_parts[0])
        s_part = float(ratio_parts[1])
        total_parts = c_part + s_part
        
        cement_cft = (c_part / total_parts) * dry_vol
        cement_bags = cement_cft / 1.25
        sand_cft = (s_part / total_parts) * dry_vol
        
        total_cost = (cement_bags * cement_price) + (sand_cft * sand_price)
        
        st.success(f"**Total Plaster Area:** {plaster_area} Sq. Ft. (Wastage Included: {wastage_pct}%)")
        
        c1, c2, c3 = st.columns(3)
        c1.metric("Cement Required", f"{cement_bags:.2f} Bags")
        c2.metric("Sand Required", f"{sand_cft:.2f} CFT")
        c3.metric("Estimated Material Cost", f"BDT {total_cost:,.2f}")
        
        # PDF Generation
        report_data = {
            "Plaster Area": f"{plaster_area} Sq. Ft.",
            "Thickness": plaster_thick,
            "Mix Ratio": mix_ratio,
            "Wastage Allowance": f"{wastage_pct}%",
            "Cement Required": f"{cement_bags:.2f} Bags",
            "Sand Required": f"{sand_cft:.2f} CFT",
            "Estimated Total Cost": f"BDT {total_cost:,.2f}"
        }
        pdf_bytes = generate_pdf("Plastering Estimation", report_data)
        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_bytes,
            file_name="plastering_report.pdf",
            mime="application/pdf"
        )
